<?php

namespace Core;

use Exception;

class Authenticator
{
    public function attempt($email, $password)
    {

        try {
            $user = App::resolve(Database::class)
            ->query('select * from users where email = :email', [
            'email' => $email
        ])->find();

        if ($user) {
            if (password_verify($password, $user['password'])) {
                $this->login([
                    'email' => $email
                ]);

                return true;
            }
        }

        return false;
        } catch(Exception $e) {
            throw new Exception("Authenticator failed " .$e->getMessage());
        }
        
    }

    public function login($user)
    {
        $_SESSION['user'] = [
            'email' => $user['email']
        ];

        session_regenerate_id(true);
    }

    public function logout()
    {
        Session::destroy();
    }
}